### ISSUE TITLE
Redrawing the timeline when outlier gets filtered out

### ISSUE THREAD

**Issue by szczura** [RickLeinecker/SeeShells#136]
When filtering the timeline, we make the filtered out events invisible. This can be an issue aesthetically when the first or last events are filtered out since the timeline will still scroll all the way to their time points when there's nothing to look at.

For this issue to close, the timeline needs to be redraw after filtering to take into account new start/end dates for the beginning and end of the timeline.

**Comment by AlekStoyanov** [comment]
No longer an issue, since the timeline is rebuilt from scratch every time filtering occurs.

**Comment by klaki892** [comment]
> No longer an issue, since the timeline is rebuilt from scratch every time filtering occurs.
(specifically fixed in #186 )
