### ISSUE TITLE
Refactor PropertyNames of IShellItems to centralized location

### ISSUE THREAD

**Issue by klaki892** [RickLeinecker/SeeShells#177]
Right now literal strings are used when defining the Key names in `getAllProperties()`

Because each ShellBag has its own special properties, these Key names are defined in their respective classes. 
However, becuase we have embedded many types and additional values (e.g. the registry decorators) we have consistent knowledge about the key names and should centralize such values to prevent errors in naming conventions (capitalized vs non-capitalized, etc.)

This becomes an issue as new filters (e.g. #176) rely on `GetAllProperties()` having a consistent name for a specific property.

Acceptance Criteria:
- Move known Key names embedded in shellitems & supporting classes (e.g. registry decorator) to a centralized location. Refactoring the parsing to use these constants instead of dispersed literal values.

**Comment by klaki892** [comment]
Optionally we may want to expose this list of known Key values to be exposed to the Embedded Scripting parser to prevent inconsistencies in scripts for existing properties (e.g. the 3 main date types)

**Comment by szczura** [comment]
Resolved by #328
