### ISSUE TITLE
Rescaling of WPF UI 

### ISSUE THREAD

**Issue by klaki892** [RickLeinecker/SeeShells#188]
Currently the does not scale properly due to various constraits and behaviors from the existing UI. Because of these oddities in scaling, UI elements might appear to big or wont scale to certain resolutions that were not originally designed against. Examples:
![image](https://user-images.githubusercontent.com/17878901/75397805-ca0ef180-58c5-11ea-8cc8-3ebd861c3680.png)

![image](https://user-images.githubusercontent.com/17878901/75397812-d2672c80-58c5-11ea-95ae-346ecf5428c9.png)

Acceptance Criteria:
- Windows and elements need to be scaled such that the entire window is taken up regardless of resolution
- elements of UI need to have min/max scaling such that they are still readable at _reasonable_ resolutions and aspect ratios.

**Comment by bridCquinn** [comment]
Remastering the Graphical WPF:
- Take out the tabs
- Resize the GUI for smaller screen
- Change colors to be easily readable

**Comment by klaki892** [comment]
> * Take out the tabs

This task duplicates one of the acceptance criteria of #189
