### ISSUE TITLE
WPF: Retrieve username locations from a configurable location

### ISSUE THREAD

**Issue by klaki892** [RickLeinecker/SeeShells#191]
In #185 It was revealed that the user's name needs to be parsed out of different strings that exist around `NTUser.dat` by hardcoding one value to pull the username. Because the current path of registry keys (and the parsed string) is only valid for how Vista-Win10 handles username support, the ability to retrieve usernames for offline (and by extension online) hives needs to be configurable to support either past systems (windows xp) or future systems.

Acceptance Criteria:
- Retrieval of username from an offline hive is no longer reliant on a hardcoded value in the code.
- OS configuration JSON files support methods of retrieving username locations from registry keys.

**Comment by szczura** [comment]
Adding wontfix label due to timing & this being a stretch goal that is not included in our requirements.
