### ISSUE TITLE
Website Download program link

### ISSUE THREAD

**Issue by szczura** [RickLeinecker/SeeShells#21]
As an investigator or regular user, I want to click on a download link for SeeShells.

**Comment by szczura** [comment]
Button has been added.

**Comment by szczura** [comment]
On hold until we have a complete program and download location

**Comment by yara-58** [comment]
#199

**Comment by klaki892** [comment]
Last line of Github's linking to releases help page is all you need:
https://help.github.com/en/github/administering-a-repository/linking-to-releases
