### ISSUE TITLE
Obtain and Display Time based Registry Metadata for ShellItems 

### ISSUE THREAD

**Issue by klaki892** [RickLeinecker/SeeShells#276]
Currently many Shellitems which are parsed from a hive dont appear on the timeline due to having no dates associated with them. (by design) 

However It has been found that many ShellBag types dont write the date information inside the shellbags themselves. An example of such is the [Network Location Shellbag Type](https://github.com/libyal/libfwsi/blob/master/documentation/Windows%20Shell%20Item%20format.asciidoc#35-network-location-shell-item)  which while in theory should write dates, does not write any date information when a user connects to a network share server. 
Instead it has been observed that although none of the dates are written inside of the shellbag itself, the shellbag is still created and the Registry contains information about when a registry key was last written too. In the case of Network Locations, this tends to be the last, first or only connection to the network share. 
This is still relevant information and although not in the Shellbag's value itself is still valuble metadata which is always present in the shellbag's registry key. (The example of Network location was used because of the case study #48 involving such shellbag types)

In an effort to provide complete traceable information for various different ShellBag types, Registry Metadata surrounding the Shellbag involving key dates of actions should also be pulled during SeeShells Parsing and presented in the final report (timeline or other export method) 

It has been observed that the [_Last Modified Time_ of a registry key](https://stackoverflow.com/q/15621053) can be obtained, other similar date information should also be obtained.

Acceptance Criteria:
- Last Modified time for registry keys should be recorded in returned ShellItem information
- Research should be done on obtaining other forms of relevant registry data and dates if present in the registry keys for ShellBags and if retrievable, should be obtained as well.

**Comment by klaki892** [comment]
Last Modified time from live(online) hives has been addressed in #271 
Work on Offline hives still needs to be done.

**Comment by szczura** [comment]
Resolved with the completion of #281 in PR #300
