### ISSUE TITLE
WPF download configuration files from database

### ISSUE THREAD

**Issue by szczura** [RickLeinecker/SeeShells#30]
As an investigator or regular user, I want to download configuration files from a database to parse ShellBags.
- Hit the OS & Locations endpoint and parse the JSON object
- Hit the GUID endpoint and parse the JSON object
- Hit the Scripts endpoint and parse the JSON

**Comment by klaki892** [comment]
This issue has had work done on it in #110  and #108, (and their respective PR's) the functionality exists behind the buttons except the scripting API. (But the buttons themselves havent been wired to use these methods.
